services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:16
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  demo-app:
    build:
      context: ./application
    image: aws-lab-java/demo-app:local
    environment:
      DEPLOYMENT_TARGET: compose
      DEMO_AUTH_TOKEN: local-token
      FEATURE_S3_METADATA: "false"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres-data: {}
