spring:
  config:
    activate:
      on-profile: local

app:
  deployment-target: ${DEPLOYMENT_TARGET:local}
  feature:
    s3-metadata: ${FEATURE_S3_METADATA:false}
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:3000}
