app:
  name: "AWS Lab Java Demo"
  owner: "Dean Lofts"
  auth-token: ${DEMO_AUTH_TOKEN:demo-token}

server:
  port: ${SERVER_PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: aws-lab-java-demo
  main:
    banner-mode: "off"
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/demo}
    username: ${SPRING_DATASOURCE_USERNAME:demo}
    password: ${SPRING_DATASOURCE_PASSWORD:demo}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        jdbc.time_zone: UTC
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
      show-components: when_authorized
      roles: ACTUATOR

logging:
  level:
    root: INFO
    com.deanlofts.awslabjava.application: INFO
