---
- name: Install Docker on Ubuntu via official repo
  hosts: all
  become: true
  vars:
    docker_packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install prerequisites
      apt:
        name: "{{ docker_packages }}"
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Ensure Docker service is enabled and running
      systemd:
        name: docker
        enabled: yes
        state: started

